/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface RjsHello {}
}

declare global {


  interface HTMLRjsHelloElement extends Components.RjsHello, HTMLStencilElement {}
  var HTMLRjsHelloElement: {
    prototype: HTMLRjsHelloElement;
    new (): HTMLRjsHelloElement;
  };
  interface HTMLElementTagNameMap {
    'rjs-hello': HTMLRjsHelloElement;
  }
}

declare namespace LocalJSX {
  interface RjsHello {}

  interface IntrinsicElements {
    'rjs-hello': RjsHello;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'rjs-hello': LocalJSX.RjsHello & JSXBase.HTMLAttributes<HTMLRjsHelloElement>;
    }
  }
}


